### ISSUE TITLE
Teleport Bypass

### ISSUE THREAD

**Issue by ghost** [OneAddictions/SkidBlocker-Issues#10]
Server Version: 1.8.8
Anticheat Version: 1.2.1 or whatever the newest version is
ProtocolLib Version: 4.4.0 or whatever the newest version is
Issue: teleport bypass and set the teleport range to 4 and dont move just left click and it will work but you can turn your head around to move directions
Client Download: http://www.mediafire.com/file/chz1un91l436o49/Ramen.rar

**Comment by OneAddictions** [comment]
Fixed the fly bypasses, currently working on the Speed bypasses, this teleport will be fixed soon!
