### ISSUE TITLE
Speed Bypass v3

### ISSUE THREAD

**Issue by ghost** [OneAddictions/SkidBlocker-Issues#11]
Server Version: 1.8.8
Anticheat Version: 1.2.1 or whatever the newest version is
ProtocolLib Version: 4.4.0 or whatever the newest version is
Issue: Speed Bypass on the ramen client use speed mode latest

**Comment by OneAddictions** [comment]
Fly bypass (old ncp) did not bypass you have to be higher than 2 blocks, and patched longjump for ncp and aac v3 (fixing teleport rn)
