### ISSUE TITLE
Waterspeed / Jesus bypass

### ISSUE THREAD

**Issue by xKeksbyte** [OneAddictions/SkidBlocker-Issues#12]
Server Version:1.8.8
Anticheat Version:Latest
ProtocolLib Version:Latest
Issue:Bypass
Client: AntiLeg1t (my private client)

The Jesus working with setPosition

for more infos how the jesus work, dm me on discord: xKeksbyte...󠀀󠀀󠀀󠀀󠀀#3261

**Comment by OneAddictions** [comment]
Sorry, but I aint patching some client that noone has.
