### ISSUE TITLE
Nofall Bypass

### ISSUE THREAD

**Issue by xKeksbyte** [OneAddictions/SkidBlocker-Issues#13]
Server Version:1.8.8
Anticheat Version:Latest
ProtocolLib Version:Latest
Issue:Bypass
Client: AntiLeg1t (my private client)

Code:
if (mc.thePlayer.fallDistance > 3) {
		Utils.setGround(true); //c03packetplayer
		mc.thePlayer.fallDistance = 3.3F;
		}

**Comment by OneAddictions** [comment]
Thanks, I have a test client of my own, thanks for sending the code!

**Comment by xKeksbyte** [comment]
no problem :D
