### ISSUE TITLE
Gravity A false flag

### ISSUE THREAD

**Issue by ghost** [OneAddictions/SkidBlocker-Issues#14]
Server Version: 1.8.8
Anticheat Version: 1.4.1 or whatever the newest version is
ProtocolLib Version: 4.4.0 or whatever the newest version is
Issue: Gravity A false flag get stairs that go up ten blocks put slime blocks at the bottom then jump on to it and it will false flag Gravity A 

https://streamable.com/qvt30

**Comment by OneAddictions** [comment]
I don't have accounting for slimes implemented will fix!
