### ISSUE TITLE
Criticals Bypass

### ISSUE THREAD

**Issue by ghost** [OneAddictions/SkidBlocker-Issues#16]
Client: Proton b13
Anticheat Version: 1.4.1 or whatever the newest version is
Bypass: Criticals
Download to the client: http://www.mediafire.com/file/if52aeqon25mqx7/Proton_b13_Velt_Disabler_Fix.rar/file

source code to it https://ghostbin.com/paste/w3ope

**Comment by OneAddictions** [comment]
Criticals aint big deal, im gonna be adding timer check that will get it
