### ISSUE TITLE
Fly Bypass

### ISSUE THREAD

**Issue by ghost** [OneAddictions/SkidBlocker-Issues#18]
Client: Liquidbounce
Anticheat Version: 1.4.1 or whatever the newest version is
Bypass: Fly mode aac3.3.12-glide
Download to the client: https://dl.ccbluex.net/download/index.php?file=TGlxdWlkQm91bmNlLzEuOC9ha3VtYS9MaXF1aWRCb3VuY2UxLjguOS1iNjIuemlw

**Comment by OneAddictions** [comment]
Will look into, thanks for notifying me, I've been sick and haven't worked on the anticheat
