### ISSUE TITLE
Jesus B / C False Flag

### ISSUE THREAD

**Issue by ghost** [OneAddictions/SkidBlocker-Issues#20]
Server Version: 1.8.8
Anticheat Version: 1.4.1 or whatever the newest version is
ProtocolLib Version: 4.4.0 or whatever the newest version is
Issue: Jesus B / C False Flag
Video Of False Flag: https://streamable.com/j963l
put on depth strider 3 boots and go down water like it was shown in the video it will false Jesus B / C

**Comment by OneAddictions** [comment]
fixed
