### ISSUE TITLE
Fly Bypass v2

### ISSUE THREAD

**Issue by ghost** [OneAddictions/SkidBlocker-Issues#22]
Client: Amera 2.0 the og aac client
Anticheat Version: 1.4.1 or whatever the newest version is
Bypass: Glide
Download to the client: https://ameraclient.webnode.com
Video :https://streamable.com/xvcbi
Glide settings: falldistance 3.0 boost 1.1 speed 0.01 and mode aac1.9.10

**Comment by OneAddictions** [comment]
fixing
