### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by OneAddictions** [OneAddictions/SkidBlocker-Issues#6]
**BYPASS FORMAT**
Putting "Latest" is not allowed

Client:
Anticheat Version: (latest is not allowed)
Bypass:
Download to the client: (if premium not required)
**ISSUE FORMAT**
Putting "Latest" is not allowed

Server Version:
Anticheat Version: 
ProtocolLib Version:
Issue:

**Comment by ghost** [comment]
What about this one for false flag / issue format 
How you trigger the false positive?
Describe how to trigger the false positive here:

Videos:
If you recorded a video of false positive, put link here: 

Anticheat Version:
Server Version:
ProtocolLib Version:
